In [1]:
import torch

In [2]:
def intialize_model_paramerters():
  torch.manual_seed(42)
  xt = torch.randn(5)
  s = torch.zeros_like(xt)
  W = torch.rand(1)
  U = torch.rand(1)
  V = torch.rand(1)
  return xt,s,W,U,V

In [3]:
def RNN():
  parm = intialize_model_paramerters()
  xt = parm[0]
  s = parm[1]
  W = parm[2]
  U = parm[3]
  V = parm[4]
  for i in range(len(xt)):
    if i != 0 :
      s[i] = torch.tanh(W*xt[i] + U * s[i-1])
    else:
      s[i] = torch.tanh(W*xt[i])

    sig = torch.nn.Sigmoid()
    Y = sig(V*s[i])
    print(s)
    print(Y)
RNN()


tensor([0.2846, 0.0000, 0.0000, 0.0000, 0.0000])
tensor([0.5525])
tensor([0.2846, 0.2670, 0.0000, 0.0000, 0.0000])
tensor([0.5493])
tensor([0.2846, 0.2670, 0.3412, 0.0000, 0.0000])
tensor([0.5629])
tensor([0.2846, 0.2670, 0.3412, 0.3747, 0.0000])
tensor([0.5690])
tensor([ 0.2846,  0.2670,  0.3412,  0.3747, -0.6431])
tensor([0.3831])
